name: Django CI

on:
  push:
    branches: [ "main", "develop", "develop-workflow" ]
  pull_request:
    branches: [ "main", "develop" ]

env: 
  PGHOST: localhost
  PGPORT: 5432
  PGUSER: postgres
  PGDATABASE: postgres

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgrespassword
        ports:
          - 5432:5432
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.11.2']

    steps:
    - name: Vente på postgres
      run: |
        psql --version
        pg_config --version
        until pg_isready -h localhost -p 5432 -U postgres; do
          echo "Postgres er ikke klar"
          sleep 1
        done
        echo "Postgres er klar"
        psql --version
        pg_config --version
        psql -c "SELECT version();"
        psql -U postgres -h localhost -p 5432 -d postgres -c "SELECT version();"
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Installere dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Kjøre tester
      env:
        DJANGO_SECRET: ${{ secrets.DJANGO_SECRET }}
      run: |
        python manage.py test
