name: Django CI

on:
  push:
    branches: [ "main", "develop", "develop-workflow" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.11.2']

    steps:
    - name: Installere dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        psql --version
        pg_config --version
    - name: Vente på postgres
      run: |
        until pg_isready -h localhost -p 5432 -U postgres; do
          echo "Ikke klar"
          sleep 1
        done
        echo "Klar"
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Kjøre tester
      env:
        DJANGO_SECRET: ${{ secrets.DJANGO_SECRET }}
      run: |
        python manage.py test
